### ISSUE TITLE
how to deal with the output of the G after training

### ISSUE THREAD

**Issue by LJT610** [sdv-dev/CTGAN#109]
* CTGAN version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csala** [comment]
Hello @LJT610 can you explain a bit what the question is?

**Comment by LJT610** [comment]
Hello @csala ,I am wondering how you deal with the discrete data generated by Generator ? For example, I train the network by adult data , and the Generator generates discrete data and continuous data, the generated discrete data may be <0, but the ordinal discrete data before trainging is ont-hot .

**Comment by LJT610** [comment]
one-hot, sorry :(

**Comment by csala** [comment]
Please have a look at the [CopulaGAN model in SDV](https://sdv.dev/SDV/user_guides/single_table/copulagan.html) which wraps around CTGAN and provides a distribution modeling layer that [ensures that the values stay within the original range](https://github.com/sdv-dev/SDV/issues/200) while also improving the overall quality of the data.
