### ISSUE TITLE
How to make training utilizes gpu?

### ISSUE THREAD

**Issue by SasikiranJ** [sdv-dev/CTGAN#110]
* CTGAN version:
* Python version:
* Operating System:

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by csala** [comment]
Hello @SasikiranJ can you provide some context and explain a bit what the question is?

**Comment by SasikiranJ** [comment]
when i am doing training on dataset it is using only cpu even though gpu exists and taking long time for training. I think if we can make model train on gpu it will train faster ?

**Comment by csala** [comment]
Got it, thanks for the details.

CTGAN always tries to use the GPU by default, so if your system has one available you should see it being used. If it is not, you may have installed a PyTorch version which is not compatible with the CUDA version of your GPU drivers.

Please have a look at the [PyTorch installation guides](https://pytorch.org/get-started/locally/) to find the right version to install.

**Comment by SasikiranJ** [comment]
I am using kaggle notebooks for that. I think gpu readily available there

**Comment by csala** [comment]
You just need to ensure that running `torch.cuda.is_available()` returns `True`. If that happens, CTGAN will use the GPU.

If you get a `False`, the problem is related to the Kaggle notebooks setup, so you may want to search for pointers there.

**Comment by SasikiranJ** [comment]
Ok. Thank you
