### ISSUE TITLE
Conditional Sampling

### ISSUE THREAD

**Issue by dimaanor** [sdv-dev/CTGAN#119]
* CTGAN version: 0.3.0
* Python version: 3.6.10
* Operating System: Amazon Linux AMI 2018.03

### Description

How can I conditionally sample the CTGAN model? Would inputting a similar encoding (as described in the paper) to the generator, but instead using a multi-hot encoding for several columns, work?

**Comment by fealho** [comment]
Hi @dimaanor. You can pass the name of the column and the value for the column to the sample method [here](https://github.com/sdv-dev/CTGAN/blob/master/ctgan/synthesizers/ctgan.py#L393). Also, for better support, we recommend using CTGAN through SDV, which provides additional functionality and more user friendly APIs for conditional sampling.
