### ISSUE TITLE
Near-zero variance problem

### ISSUE THREAD

**Issue by Iris-Di** [sdv-dev/CTGAN#120]
Hi there,

We found that maybe because our data have a near-zero variance, CTGAN could not learn well from this column.  There is almost no correlation between the real data and the CTGAN data for this column. Is there any solution?

**Comment by csala** [comment]
Hello @Iris-Di I'm a bit confused about what the problem that you are describing. Would you mind providing some more details and maybe showing an example?

**Comment by fealho** [comment]
HI @Iris-Di, I'll be closing the issue since you haven't provided further details in a while. Feel free to reopen it in case this is still an issue.
