### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Aksh97** [sdv-dev/CTGAN#121]
* CTGAN version: v0.3.0
* Python version: 3.8.3
* Operating System: Windows 10

### Description

For every dataset I pass, I get the error :
**ValueError: max() arg is an empty sequence**

Before the error prints and it halts, it shows:
ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)

### What I Did
ctgan.fit(data, epochs=100)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
/usr/local/lib/python3.6/dist-packages/sklearn/mixture/_base.py:267: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/mixture/_base.py:267: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/mixture/_base.py:267: ConvergenceWarning: Initialization 1 did not converge. Try different init parameters, or increase max_iter, tol or check for degenerate data.
  % (init + 1), ConvergenceWarning)

```

**Comment by csala** [comment]
Hello @Aksh97 You are hitting issue #115 which as already been resolved. [Here you have instructions about how to work around it](https://github.com/sdv-dev/CTGAN/issues/115#issuecomment-750403870) until a new release is made, which will be done later this week.
