### ISSUE TITLE
Version discrepancies breaking a lot of the code I find that depends upon this package, more a question of curiosity

### ISSUE THREAD

**Issue by HarrisonWilde** [sdv-dev/CTGAN#122]
* CTGAN version: 0.3.1 and 0.2.2.dev1
* Python version: 3.8.5
* Operating System: Mac OS

### Description

Hi, this is somewhat of a question rather than an issue, I am using CTGAN as a base for code I have found elsewhere https://github.com/Tecnarca/patectsdgym/blob/master/sdk/patectgan/architectures/dpctgan.py and https://github.com/opendifferentialprivacy/smartnoise-sdk/blob/master/sdk/opendp/smartnoise/synthesizers/pytorch/nn/dpctgan.py etc. but find that it doesn't work with the new version of the ctgan package; I instead must install 0.2.2.dev1 as in the test requirements of smart noise's repo.

I was interested to know why was the ctgan.conditional module removed after this version and if there is an equivalent in the newer version to the ConditionalGenerator etc.

### What I Did

N/A

**Comment by fealho** [comment]
Hi @HarrisonWilde, we redesigned the API in v0.3.0 to be easier to use while still providing the same functionality. The `ConditionalGenerator` that you mentioned has been merged with other parts of the code, so you should still be able to do what you were doing before.
