### ISSUE TITLE
Question about the PMF calculation in the Training-by-Sampling method

### ISSUE THREAD

**Issue by imkhoa99** [sdv-dev/CTGAN#125]
I have one question to which I could not find the answer anywhere that I think you could clarify me. In the Training-by-Sampling method, it calculated the PMF value for each value in the discrete column D_i.

![Training by Sampling Process](https://user-images.githubusercontent.com/41847533/108064287-1ddd9200-7065-11eb-954d-64d528acf6dd.png)

Could someone explain why do we need to calculate the PMF value in the method? In the next step, it stated to select the value randomly according to the PMF above, does it mean it chooses the value having the highest PMF in this case?

**Comment by leix28** [comment]
Let me give an example. In a table, there is a column containing 2 categorical values A and B, and another categorical column containing C, D, and E. There are a few numerical columns. 

| | | | |
|:---:|:---:|:---:|:---:|
|A|C|0.5|...|
|A|D|0.6|...|
|B|C|0.1|...|

Assume that in this data, 9900 rows have A while only 100 rows have B. 

- (Step 1) We will create an all zero vector m_1=[0, 0], m_2=[0, 0, 0]
- (Step 2) We will uniformly pick from the first or the second column. Assume that we pick the first column. 
- (Step 3) We will compute a probability following the log-frequency, i.e. A:B = log(9900):log(100)=1.998. So in the PMF, p(A)=66%, p(B)=34%.
- (Step 4, 5) We will sample from the PMF in step 3. i.e we will have 66% to sample an A and 34% to sample a B. If we get an A, then we will set m_1 to [1, 0]. If we get a B, then we will set m_1 to [0, 1]
- (Step 6) Depending on what we get from the last step, we will have [1, 0, 0, 0, 0] or [0, 1, 0, 0, 0].

What if in step 3, we don't compute the log frequency PMF?
- In this example, we will see that our model get trained a lot (99%) on generating A, but little chance (1%) to generate B. Then the model has significantly lower quality when it tries to generate rows with B.

**Comment by imkhoa99** [comment]
Thanks @leix28! I got it! It is true that having the log-frequency allows the model to explore available categories more evenly.
