### ISSUE TITLE
Any way to fix one or more categorical variable value during the data generating stage?

### ISSUE THREAD

**Issue by ericwang915** [sdv-dev/CTGAN#13]
Thank you for the great works! 

In the case when I want to fix one or two categorical columns' value before generating the data. What would be the ideal way to do it? If it is not a current feature, will you consider supporting it in the future?

For example, instead of generating random 1000 samples for the Adult Census Dataset. I want to generate 1000 samples with Income <= 50k

Any suggestion will be much appreciated!

**Comment by kevinykuo** [comment]
Sampling is cheap so you could just sample a bunch of records then filter for the ones you're interested in.

**Comment by csala** [comment]
> Sampling is cheap so you could just sample a bunch of records then filter for the ones you're interested in.

Exactly what @kevinykuo says: right now there is no way to fix variables when sampling, so the only option is to discard the invalid rows and resample until you have as many as you need.

Another option is, is you know what you need in advance, to create a subset of the original dataset with only the rows that contain the value(s) that you need and then fitting a specific CTGAN instance with that subset of rows so all the newly generated ones have those values fixed.

**Comment by pawelkuk** [comment]
> > Sampling is cheap so you could just sample a bunch of records then filter for the ones you're interested in.
> 
> Exactly what @kevinykuo says: right now there is no way to fix variables when sampling, so the only option is to discard the invalid rows and resample until you have as many as you need.
> 
> Another option is, is you know what you need in advance, to create a subset of the original dataset with only the rows that contain the value(s) that you need and then fitting a specific CTGAN instance with that subset of rows so all the newly generated ones have those values fixed.

What about setting `condvec` by hand while sampling? Shouldn't we then get the desired class most of the time?

**Comment by MotoRZR** [comment]
This is exactly the feature I’m looking for.  Would be a great addition

**Comment by csala** [comment]
This feature has been covered in the PR #68
