### ISSUE TITLE
ValueError from validate_discrete_columns with uniqueCombinationConstraint

### ISSUE THREAD

**Issue by MLjungg** [sdv-dev/CTGAN#133]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* CTGAN version: 0.4.0
* Python version: 3.7
* Operating System: macOS

### Error Description

When adding an uniqueCombinationConstraint a ValueError is raised from validate_discrete_columns in the "fit" method of CTGAN. My understanding is that it occurs because the parameter "discrete columns" is defined based on the original data and not from the transformed data after the constraint is applied.

It seems to trace back to the following PR: https://github.com/sdv-dev/CTGAN/pull/118.

### Steps to reproduce

Add an uniqueCombinationConstraint with "transform" as the handling_strategy.

**Comment by fealho** [comment]
Good catch! As you mentioned, the problem is actually in SDV, `validate_discrete_columns` is only doing its job and catching the error instead of letting it run silently. I'm working on a fix so this should be patched soon. Thanks for bringing this to our attention 👍
