### ISSUE TITLE
How can I generate values that are equal or higher than 0

### ISSUE THREAD

**Issue by apavlo89** [sdv-dev/CTGAN#142]
Is there a way I can generate rows with this parameter? Thanks!

**Comment by fealho** [comment]
Hi @apavlo89 if you want to add constraints to the data I recommend using CTGAN through [SDV](https://github.com/sdv-dev/SDV). For a tutorial on how to use it, check [here](https://sdv.dev/SDV/user_guides/single_table/ctgan.html).
