### ISSUE TITLE
TVAE: loss function

### ISSUE THREAD

**Issue by DingfanChen** [sdv-dev/CTGAN#143]
The current implementation of the loss function in TVAE employs a Gaussian distribution for the mode indicator variable $\beta$ (and the loss is only computed for the last dimension of the variable $\beta$), which seems inconsistent with the description in the paper.

Replacing the "or" by "and" in Line 57 seems to solve this issue, or if I miss anything? Thanks.

**Comment by fealho** [comment]
Hi @DingfanChen, that's a very good catch! You are correct, I'll fix this issue as soon as possible. Thanks for notifying us :thumbsup:.
