### ISSUE TITLE
Add callback

### ISSUE THREAD

**Issue by FlorentRamb** [sdv-dev/CTGAN#149]
### Problem Description

Adding a callback during training would allow to implement an early stop strategy (using for instance the _NMI_ or the score of a supervised task), or at least to print additional information. 

### Expected behavior

The callback will be fed to the `fit` method of `CTGANSynthesizer`. It could add one argument: a dictionary containing one key with the callback class and another key with the parameters of that callback.

The callback will be instantiated before the training loop and will also take as argument the `synthesizer`. A flag `_stop_training` must be added to `CTGANSynthesizer` to perform early stop (as it could be updated by the callback).

A `BaseCallback` can be defined (with methods as `on_epoch_end`, `on_epoch_start`, ...) and the users will need to overload this base class.

Note that I'm willing to work on this if you want!

**Comment by pvk-developer** [comment]
Hello @FlorentRamb , thank you for your proposition. 

We will have a discussion with our engineering team whether or not we want to add this in the future or not. We will move the discussions here if that's the case. 

Thank you

**Comment by xamm** [comment]
I changed the PR to showcase what my Idea would be and described it in [this](https://github.com/sdv-dev/CTGAN/pull/196#issuecomment-993346875) comment in the PR.
