### ISSUE TITLE
Different shapes after running data_transformer.py

### ISSUE THREAD

**Issue by ItsyPetkov** [sdv-dev/CTGAN#155]
Hi, why does transforming the same data multiple times lead to different results. I tried this a couple of times while testing a different model and I noticed the transformed data had a different shape every time I run the code. Why is this so?

**Comment by npatki** [comment]
Hi, to answer your Q, we need a bit more info.

Can you clarify a bit about what you mean by "transforming the same data multiple times"? Are you taking the same exact input data and noticing different outcomes every time it's transformed? Or are you taking the initial data `D`, transforming it to `D'` and then transforming `D'` again into `D''`?

Also, what are the changes in shapes you're observing (increase vs. decrease, rows vs. columns, etc.)?

**Comment by fealho** [comment]
Another possible cause is that the [bayesian GMM](https://github.com/sdv-dev/CTGAN/blob/master/ctgan/data_transformer.py#L36) used to transform continuous values isn't deterministic. Basically, it works by transforming the continuous values into a new vector representation with of (N+1) dimensions, where N is the number of clusters. The value N is learned from the data and can vary every time you run the code. If you want to avoid this, I believe setting the random seed to some constant value should help.

**Comment by fealho** [comment]
I'll be closing this issue, since it seems like your question was answered. Feel free to reopen it if you need further clarification.
