### ISSUE TITLE
'Unexpected value {value} in synthetic data.

### ISSUE THREAD

**Issue by Zepp3** [sdv-dev/CTGAN#157]
Hi!

Does anyone know how the following warning arises?

```
/usr/local/lib/python3.8/dist-packages/sdmetrics/utils.py:62: UserWarning: Unexpected value False in synthetic data.
  warnings.warn(f'Unexpected value {value} in synthetic data.')
```

The string `False` is just an example, the warning appears with every string in the dataset.

**Comment by pvk-developer** [comment]
Hi @Zepp3 , this warning actually arises from `sdmetrics`, I assume when you are trying to `evaluate` your synthetic data. You can ask this question on [SDMetrics](https://github.com/sdv-dev/SDMetrics/) library. I will close this one here.
