### ISSUE TITLE
A small error in your code

### ISSUE THREAD

**Issue by ori-katz100** [sdv-dev/CTGAN#158]
Hello,
I think that you have a mistake in the file "ctgan.py" line 363: you wrote "fake_cat = fake" but it should be "fake_cat = fakeact".

Best,
Ori

**Comment by fealho** [comment]
Hi @ori-katz100, that's a great catch! It actually improves performance quite a bit, so thanks a lot!

**Comment by Baukebrenninkmeijer** [comment]
Oh wow, this is a super important difference :')
