### ISSUE TITLE
Generated new data contains Unexpected Values.

### ISSUE THREAD

**Issue by MariamDundua** [sdv-dev/CTGAN#162]
### Environment details

* CTGAN version:
* Python version:3.8.3
* Operating System: Windows 10

### Problem description

I have a pandas data frame (50000,20) with several continuous columns. Some of them are non-negative because of their meaning. But generated data contains negative values as well. What is the reason? I trained Ctgan on 50 epoch

**Comment by tjhallum** [comment]
I'm having a very similar issue. I have a data set of events and each event occurs on a day of the month. Within the original data set, the day_of_mo column ranges from 1 to 31...however, CTGAN produced several synthetic events with day_of_mo values that were greater than 31.

Notably, I did instantiate the CTGAN model object using the default arguments (specifically, min_value & max_value set to 'auto'). 

According to the documentation, when these default arguments are used for min_value & max_value "[the model will learn the upper and lower bounds of the input data, and use that for sampling. This means that all sampled data will be between the maximum and minimum values found in the original dataset for each numeric column.](https://sdv.dev/SDV/user_guides/single_table/ctgan.html#:~:text=the%20model%20will%20learn%20the%20upper%20and%20lower%20bounds%20of%20the%20input%20data%2C%20and%20use%20that%20for%20sampling.%20This%20means%20that%20all%20sampled%20data%20will%20be%20between%20the%20maximum%20and%20minimum%20values%20found%20in%20the%20original%20dataset%20for%20each%20numeric%20column.)" <-- This statement describes exactly what I'm trying to achieve...but this does not appear to be what CTGAN is actually doing.

**Comment by MariamDundua** [comment]
I am using CTGANSynthesizer.
Here is my code

from ctgan import CTGANSynthesizer
ctgan = CTGANSynthesizer()
ctgan.fit(data, discrete_columns,epochs=50)
Is there the same solution for my model?

**Comment by tjhallum** [comment]
@MariamDundua,

I received a [working solution](https://github.com/sdv-dev/SDV/issues/513#issuecomment-879172814) over on the `sdv` GitHub.

The short story is that they just published the latest release of `sdv` yesterday - 0.11.0.

With that version of `sdv` this issue of unexpected values with `CTGAN` has been resolved.

`pip install sdv==0.11.0`

Then, fully restart your Jupyter Notebook/data science environment and re-import `sdv`.

At that point, you can employ CTGAN using the same syntax illustrated in my example above and it will correctly ensure that all sampled data will be between the maximum and minimum values found in the original dataset for each numeric column.

**Comment by MariamDundua** [comment]
Thank you, It's works
