### ISSUE TITLE
How to use SDV Constraints within CTGANSynthesizer Class ?

### ISSUE THREAD

**Issue by saichaitanyamolabanti** [sdv-dev/CTGAN#165]
I have to use CTGANSynthesizer class because it treats discrete and continuous columns separately and while searching online i found constraints can only be included in CTGAN class which comes from SDV library. So, can anyone help me how to utilize Constraints in CTGANSynthesizer class which comes from ctgan library.

**Comment by csala** [comment]
[This was responded on the SDV Slack space](https://app.slack.com/client/T017A503B3M/C01736V6ME2/thread/C01736V6ME2-1627580635.051000), so it can be closed.

Reproducing the response here:

> The CTGAN class does actually allow modeling discrete variables. For that you just need to specify their type as `categorical`. You can see a related question responded here: https://github.com/sdv-dev/SDV/issues/445

**Comment by Rajeswari-gn** [comment]
> I have to use CTGANSynthesizer class because it treats discrete and continuous columns separately and while searching online i found constraints can only be included in CTGAN class which comes from SDV library. So, can anyone help me how to utilize Constraints in CTGANSynthesizer class which comes from ctgan library.

Were you able to solve this problem? Is the solution posted on github?
