### ISSUE TITLE
Making training progress visible to the user

### ISSUE THREAD

**Issue by xamm** [sdv-dev/CTGAN#179]
### Problem Description

At the moment it is not possible to see the training progress when training a CTGAN or TVAE model.
For CTGAN logging when an epoch has finished is possible, but how long an epoch will approx. take or which batch is currently processed during an epoch is not visible.

### Expected behavior

Being able to see which batch is currently processed in a progress bar would be nice to estimate training time.

### Additional context

This could be done for example by using [`tqdm`](https://github.com/tqdm/tqdm)

**Comment by npatki** [comment]
Thanks for filing this feature request. We'll keep this open for tracking as we prioritize and make progress on it.

As somewhat of a workaround, you can currently use `verbose=True`, which will print out values for every epoch. That way, you can have at least some visibility on the progress.

**Comment by npatki** [comment]
We now have a proposed API available in #298. There are 2 changes we need to make together:

1. Updating to a progress bar and
2. Saving the loss values so you can use them later

Let's use the other issue to continue the discussion.
