### ISSUE TITLE
In TVAE code，I  can not find the parameter that for conditional sample，unlike the CTGAN code  

### ISSUE THREAD

**Issue by guoxixi1982** [sdv-dev/CTGAN#200]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* CTGAN version:
* Python version:
* Operating System:

### Steps to reproduce

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Closing this issue since we've answered the question. Please feel free to reply if there is more to discuss and I can reopen the issue.
