### ISSUE TITLE
Hello, I can't see the evaluation index after the code runs.

### ISSUE THREAD

**Issue by hhcNWPU** [sdv-dev/CTGAN#205]
Hello, I can't see the evaluation index after the code runs.
What are the evaluation indicators?
How to calculate the evaluation index? 
As a newcomer, I don't know how to evaluate a well-trained model.
Please help me.

**Comment by npatki** [comment]
Hi @hhcNWPU, nice to meet you. Could you describe what is meant by "evaluation index"?

Some general notes on evaluation:

1. You can use `verbose=True` when fitting your CTGAN model. This will print out the generator and discriminator loss at every training epoch.
2. Once you have trained your model, generate some synthetic data. You can then evaluate the synthetic data vs. the real data using the [SDMetrics](https://github.com/sdv-dev/SDMetrics) library.

**Comment by npatki** [comment]
Hello, it seems like this issue may be getting stale. I'll close it off since we've answered your question. Feel free to reply if you have more questions and I can reopen the issue for continued discussion.
