### ISSUE TITLE
Allow setting the random number generator state

### ISSUE THREAD

**Issue by katxiao** [sdv-dev/CTGAN#207]
### Problem Description

In addition to allowing a random seed, we should allow users to set the random number generator's state. This includes both the `numpy.RandomState` and also the `torch.Generator` random state.

**Comment by npatki** [comment]
This general request may apply to more than just CTGAN. Let's continue this conversation in the main SDV repo. See [Issue #586](https://github.com/sdv-dev/SDV/issues/586).
