### ISSUE TITLE
TVAE Loss?

### ISSUE THREAD

**Issue by Mfk98** [sdv-dev/CTGAN#212]
### Environment details

If you are already running CTGAN, please indicate the following details about the environment in
which you are running it:

* CTGAN version: 0.5.1
* Python version: 3.9
* Operating System: Windows 11

I was looking to plot the loss of the TVAE model
However after a few epochs the loss is a large negative number and sinking.
Example after 1000 epochs i get -72. 
I was wondering what this means and how can convert it to a positive number converging to 0.

Many Thanks

**Comment by npatki** [comment]
Hi @Mfk98, I'll close off this issue since we've answered the original question. Feel free to reply if you have any other follow ups and I can reopen the issue for more discussion.
