### ISSUE TITLE
ctgan.set_random_state() does not work   

### ISSUE THREAD

**Issue by limhasic** [sdv-dev/CTGAN#213]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* CTGAN version: 0.5.1
* Python version:  Python 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0] :: Anaconda, Inc. on linux
* Operating System: ubuntu 20.04 

### Error Description

 **just generate random numbers** 

![image](https://user-images.githubusercontent.com/63271642/165693353-c73ad347-fe53-42a7-bd26-83f4ce1e5227.png)
![image](https://user-images.githubusercontent.com/63271642/165693306-a2912752-27f1-41e4-a5e8-288baaaa06e3.png)

**after then kernel restart and run all** 

![image](https://user-images.githubusercontent.com/63271642/165693618-30e50471-c46e-42c3-a8ff-95c82d4379c8.png)
![image](https://user-images.githubusercontent.com/63271642/165693637-4743175e-fa36-42e8-af1b-59ae468159a5.png)

**without stablize torch random_seed**

  

### Steps to reproduce

from ctgan import CTGANSynthesizer
random_sample= 139
data = scaled_kon_df_total_17_1
ctgan = CTGANSynthesizer(epochs=100)
ctgan.set_random_state(0) # i thought it works but.. didn't
ctgan.fit(data, ['Group'])
samples_139_1 = ctgan.sample(random_sample)

**Does "set_random_state" only work with 0.5.2.dev0 ?**

**Comment by npatki** [comment]
Hi @limhasic, thanks for the details. The `set_random_state` should be working for version 0.5.1. And unfortunately, I am unable to replicate the issue using some demo datasets.

In order to have replicable results, it is necessary to instantiate the object, refit and resample the data. In the below code, `sample_1` and `sample_2` should be the same while `sample_3` should be different. 

```python
ctgan = CTGANSynthesizer(epochs=100)
ctgan.set_random_state(0)
ctgan.fit(data, ['Group'])
sample_1 = ctgan.sample(random_sample)

ctgan = CTGANSynthesizer(epochs=100)
ctgan.set_random_state(0)
ctgan.fit(data, ['Group'])
sample_2 = ctgan.sample(random_sample)
sample_3 = ctgan.sample(random_sample)
```

Could you try running the above code to verify this? If this is working correctly, the issue may be in something that's happening when you restart the kernel.

**Comment by npatki** [comment]
Hi @limhasic, have you gotten a chance to check this on the latest version? I'll close off the issue as obsolete, since it seems as if the more recent versions of CTGAN have fixed this issue.

Please reply if you see this bug persist and I can reopen the issue for continued investigation.

**Comment by limhasic** [comment]
Thank you for your interest.

**Comment by AndresAlgaba** [comment]
Hi there! I ran into the same problem using ctgan version 0.6.0. So the problem seems to persist. I use the following code:

``` python
from ctgan import CTGAN
from ctgan import load_demo

real_data = load_demo()
real_data = real_data[5000:]

discrete_columns = [
    'workclass',
    'education',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'native-country',
    'income'
]

ctgan = CTGAN(epochs=2)
ctgan.set_random_state(0)
ctgan.fit(real_data, discrete_columns)
sample_1 = ctgan.sample(100)

ctgan = CTGAN(epochs=2)
ctgan.set_random_state(0)
ctgan.fit(real_data, discrete_columns)
sample_2 = ctgan.sample(100)

sample_1.equals(sample_2)
```
which returns ``False``.

**Comment by AndresAlgaba** [comment]
I have created a PR in the RDT library (https://github.com/sdv-dev/RDT/pull/575). If the reproducibility is fixed there, some fix is still needed here to feed the ``random_state``.
