### ISSUE TITLE
whats the different with CTGAN and CTGANSynthesizer

### ISSUE THREAD

**Issue by limhasic** [sdv-dev/CTGAN#214]
i wonder whats the different with ctgan and CTGANSynthesizer 

numpy or sklrean version differ? 

Are there any functional differences?

**Comment by npatki** [comment]
Hi @limhasic, nice to meet you.

[`CTGANSynthesizer`](https://github.com/sdv-dev/CTGAN/blob/master/ctgan/synthesizers/ctgan.py#L96) is a class written in this library. It contains the code for the GAN-based fitting and modeling. Meanwhile, [`CTGAN`](https://github.com/sdv-dev/SDV/blob/master/sdv/tabular/ctgan.py#L92) is implemented in the SDV library as a wrapper around `CTGANSynthesizer`. It provides convenience functions such as preprocessing data, handling anonymization, primary keys, etc.

I would suggest using `CTGAN` if your goal is to create synthetic data end-to-end using a public or enterprise dataset. On the other hand if you are willing to manually clean your data or you are doing academic research on the modeling iteself, you are welcome to directly use the `CTGANSynthesizer`. 

Hope this helps!

**Comment by npatki** [comment]
Hi @limhasic, I'm closing off the issue since've we've answered your question.

Please feel free to reply if there is more you'd like to discuss and I can reopen the issue.
