### ISSUE TITLE
Use a List instead of a Bool

### ISSUE THREAD

**Issue by davebulaval** [sdv-dev/CTGAN#216]
The method `transform` of the `BayesGMMTransformer` is the [following](https://github.com/sdv-dev/RDT/blob/74ffcb72aaddf434b31f09bcbdfcda66457539b0/rdt/transformers/base.py#L232): `def transform(self, data, drop=True):` where `drop` is a bool according to the doc. However, [here](https://github.com/sdv-dev/CTGAN/blob/357177806a0523ce94a0b199c0914fd8849e51b3/ctgan/data_transformer.py#L113) during the transformation we use a list instead of a bool (`transformed = gm.transform(data, [column_name])`). 

Thus, since the transforming use [`if bool`](https://github.com/sdv-dev/RDT/blob/74ffcb72aaddf434b31f09bcbdfcda66457539b0/rdt/transformers/base.py#L255) it will always be true, thus leading to a potential bug if the intent **was not** to drop it for that specific case.

I will propose a PR with the fix depending on the original intent since it is not clear to me.

**Comment by npatki** [comment]
Hello, thanks for catching this. Note that the RDT API is changing as we integrate with the new RDT 1.0+

Seems like the default for all transformers is `drop=True`, so this may be working as intended even though the usage isn't quite correct. However, we'll clarify the original intent first in case this is a bug.

**Comment by davebulaval** [comment]
I must say that I am a little bit disappointed by your approach against "outsider" PR. It has been (I think) my third PR that I have been told is a good/interesting fix, but in the end, my code is denied. I've put some of my free time into this, and the only reward I was hoping for was at least to get some line of code in this OSP.  

You do what you want with this comment, and I will not put more effort into trying to help this OSP.
