### ISSUE TITLE
Fix flaky test associated with sampling

### ISSUE THREAD

**Issue by kevinykuo** [sdv-dev/CTGAN#22]
There's some randomness involved in https://travis-ci.org/sdv-dev/CTGAN/jobs/637977740#L250
associated with https://github.com/sdv-dev/CTGAN/pull/20

Will need to have a more generous threshold or take a few more samples. Investigating.

**Comment by csala** [comment]
@kevinykuo Let's fix it by keeping the randomness under control by using mocks.

**Comment by kevinykuo** [comment]
Realized that instead of `np.random.choice()` we can just deterministically specify the training data. Once we get the trained model I'm proposing we take more samples to lessen variance (since it's cheap to do and adds negligible testing time).
