### ISSUE TITLE
Constraints set up

### ISSUE THREAD

**Issue by WYF-GAN** [sdv-dev/CTGAN#229]
Hi professor,
I can run the CTGAN and would like to ask question about constraints setup.

### Problem description
I have seen the advanced usage of the guide. But still want to know if we can set advanced constraints other than min or max boundaries. For example, can we set variable A + variable B = constant value or range, namely, A ranges from 0 to 500, B ranges from 0 to 400, can we set the constraint that (A + B) ranges from 800 to 900? 

Thanks you!

Regards,
Yufei Wang

**Comment by npatki** [comment]
Hello @WYF-GAN, nice to meet you.

There are many constraints options that are available. Besides min/max boundaries, there are a number of other [Predefined Constraints](https://sdv.dev/SDV/user_guides/single_table/handling_constraints.html#predefined-constraints) that you can use. I would first check to see if any of these can suit your needs. If not, you can implement more complex logic by writing your own [Custom Constraint](https://sdv.dev/SDV/user_guides/single_table/custom_constraints.html).

Also, as an FYI, you can only use the constraints if you use the main SDV library. This [User Guide](https://sdv.dev/SDV/user_guides/single_table/ctgan.html) has more information. Make sure the CTGAN object is created using --

```
from sdv.tabular import CTGAN

model = CTGAN()
```

BTW, we are not all professors :) just a group of people with some research experience passionate about building a usable library.

**Comment by WYF-GAN** [comment]
Dear authors,
Thanks for your response. I have checked the "Custon Constraint" and run the demo, however, "create_custom_constraint" can not be found from "sdv.constraints", do you know why?
Regards,
Yufei

**Comment by npatki** [comment]
Hi @WYF-GAN, the constraints API was updated recently. Can you double-check to see if you have the latest version of SDV installed?

```python
>>> import sdv
>>> print(sdv.__version__)
0.16.0
```

**Comment by npatki** [comment]
Hello, I'll close this issue off since it has been stale for a few weeks.

If you are continuing to observe an error, could you file an [issue in the main SDV library](https://github.com/sdv-dev/SDV/issues/new/choose)?
