### ISSUE TITLE
Surprising results on a simple dataset

### ISSUE THREAD

**Issue by samgohan** [sdv-dev/CTGAN#230]
### Environment details

If you are already running CTGAN, please indicate the following details about the environment in
which you are running it:

* CTGAN version: 0.5.1
* Python version: 3.8.13
* Operating System: Windows 10

### Problem description

I tried to use the GAN to get synthetic data on a very simple dataset : 2 continuous variables (X,Y). But, unlike others generators, the results are very .... surprising... The X-Y link is not identified and there are synthetic data everywhere within the data space.
You can plot the sample in the attachment and then plot the GAN results. 
I tried with the default settings and then by changing "epochs", "batch_size" and "embedding_dim" but it's still bad.

[ech0.csv](https://github.com/sdv-dev/CTGAN/files/9102984/ech0.csv)

### What I already tried

The first code I tried : 
        ctgan = CTGANSynthesizer()
        ctgan.fit(ech)
        Synth = ctgan.sample(100000)
        sns.scatterplot(Synth.X,Synth.Y)

The second code but I tried different parameters values
        ctgan = CTGANSynthesizer(epochs=1000,  batch_size=1000,embedding_dim=1000)
        ctgan.fit(ech)
        Synth = ctgan.sample(100000) 
        sns.scatterplot(Synth.X,Synth.Y)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by npatki** [comment]
Hi @samgohan, nice to meet you. Appreciate the detailed code snippets and data. 

You may need to increase epochs. Here is my result of using `CTGANSynthesizer` on your data with `epochs=2500`.

![image](https://user-images.githubusercontent.com/3227804/178783698-cde48380-0546-4650-9391-0907d9189fe3.png)

Would you consider the above result unsatisfactory? Classifying it as "bad" or "awful" can be subjective. It might be helpful to use a quantifiable evaluation critera.

You also mentioned other generators. In my experience, GANs will model complex data given enough epochs, but can be a heavy-handed approach for simple data. For your specific dataset, a simpler model like the SDV's [GaussianCopula](https://sdv.dev/SDV/user_guides/single_table/gaussian_copula.html) takes a fraction of the time and produces quality data right away.

![image](https://user-images.githubusercontent.com/3227804/178784520-9c5bdde0-fd8a-4d5a-af55-809e4f06d4bf.png)

**Comment by npatki** [comment]
@samgohan No problem! Thanks for sharing your results. 

I would recommend using the SDV's GaussianCopula model instead of CTGAN. The default settings of GaussianCopula specifically work for simple data like yours.

Generally, defaults are not guaranteed to be optimal for every dataset, as there are many different factors to consider. But we will always expose and give you control over the parameters so you can tune the model.

**Comment by npatki** [comment]
Hello, I'll close this issue off since it has been stale for a few weeks and we've discussed your initial question. Please feel free to reply if there is more to discuss and I can reopen the issue.
