### ISSUE TITLE
Setting upper and lower bounds for features to generate

### ISSUE THREAD

**Issue by ayyucedemirbas** [sdv-dev/CTGAN#254]
### Problem Description

I try to generate values on Pima Indians Diabetes Database and the model generates strange values. No one, for instance, can become pregnant -2 times or have a blood pressure reading of -32.

### Expected behavior

If the users could provide ranges for each column (feature) to generate values between these upper and lower constraints before fitting the model, that would be fantastic. For instance, it would fall within 0 and 15 for pregnancy. I believe that the following would work:

    value_ranges = [("Pregnancy", 0 ,15), ("Blood Pressure", 50, 200)]
    
    ctgan.fit(..., value_ranges=value_ranges )

 I don't know whether this is possible or not. I haven't read the CTGAN paper yet.

Thank you so much!

**Comment by npatki** [comment]
Hi @ayyucedemirbas, nice to meet you! If this is your first time interacting with the `CTGAN` model, I would recommend heading over to the `sdv` library. The SDV library provides convenient wrappers around the core, CTGAN model which should solve the issue you are seeing.

[Here is a user guide](https://sdv.dev/SDV/user_guides/single_table/ctgan.html) that you can use to start with.

In the SDV, we learn the min/max values that are in your input data (real data). It will make sure that the synthetic data does not go outside of those boundaries. So in this case, as long as your real data is within the [0, 15] range, the synthetic data will as well.

Let me know if that solves your problem!

**Comment by ayyucedemirbas** [comment]
Nice to meet you too! I'll take a look at the SDV. Thank you so much!
