### ISSUE TITLE
Add verbose parameter to TVAE

### ISSUE THREAD

**Issue by candalfigomoro** [sdv-dev/CTGAN#269]
It seems not to be possible to track the progress of the fit using TVAE.

This is extremely problematic because, especially with large datasets, it is impossible to tell what epoch the model training has reached. Perhaps it is 1 hour away from the end of the training? Perhaps it is 100 years away? Who knows.

Please add a "verbose" parameter to TVAE (as already exists for CTGAN) so that the current epoch and loss can be printed.

Thank you.

**Comment by npatki** [comment]
Hi everyone, we have issue #300 with the proposed functionality that we want to add. I'll mark this issue as a duplicate. 

Feel free to look over #300 and let us know if that functionality will suit your needs. Thanks!
