### ISSUE TITLE
How to run the code without any discrete_columns？thanks

### ISSUE THREAD

**Issue by Creazy-MR** [sdv-dev/CTGAN#275]
How to run the code without any discrete_columns？thanks!

**Comment by npatki** [comment]
Hi @Creazy-MR, the `discrete_columns` parameter is optional. If you do not have any discrete columns, you can omit this parameter.

BTW for full, end-to-end usage it may be helpful to start with the SDV library. This library includes wrappers around CTGAN that will automatically help you address discrete vs. continuous columns. For more info, you can [check out the User Guide here](https://sdv.dev/SDV/user_guides/single_table/ctgan.html).

**Comment by Creazy-MR** [comment]
@npatki thanks very much！

**Comment by npatki** [comment]
@Creazy-MR no problem! Closing off this issue since we've answered the question. If you have any other follow-ups, feel free to reply and we can reopen for investigation.
