### ISSUE TITLE
Generate image of discriminator/generator loss values during `fit`

### ISSUE THREAD

**Issue by pxxxoc57** [sdv-dev/CTGAN#281]
### Problem Description
I want to trace the loss function image of the generator and discriminator, there seems to be no module in the code that is called directly

**Comment by npatki** [comment]
Hi @pxxxoc57, this is not supported yet so we can treat this issue as a feature request.

In the meantime, you can definitely save the printed loss values and plot them. [This comment in the SDV](https://github.com/sdv-dev/SDV/issues/896#issuecomment-1523643557) provides some code you can use to accomplish this.

**Comment by pxxxoc57** [comment]
> 

Hi @npatki ,I express my gratitude for the code provided, and it is an esteemed pleasure to receive communication from you.
