### ISSUE TITLE
simple script for deploying ctgan onto a server - looking for feedback

### ISSUE THREAD

**Issue by oregonpillow** [sdv-dev/CTGAN#29]
Hey guys,
huge fan of the project. I recently deployed ctgan onto a server and wrote some simple scripts to make the deployment easier. It features a simple CLI to prompt the user through the process of creating synthetic data. 

if you're interested please check out: https://github.com/oregonpillow/ctgan-server-cli

I'm very new to programming and data science and would really welcome any advice and feedback. So please have mercy on my noob programming / methods of implementation :) 
Any advice / constructive feedback would be really appreciated.

-Tim

**Comment by leix28** [comment]
Interesting project! This repo will be added to "related projects". 

Not sure if GPU can be specified in the script when there are multiple GPUs on the server?

**Comment by oregonpillow** [comment]
That's a good question, I think this should be possible. I will look into this...
I think something within [https://pytorch.org/docs/stable/cuda.html](https://pytorch.org/docs/stable/cuda.html) could provide the answer.

On a similar note, earlier today  I implemented `early stopping, patience, logging, gpu_stats` as parameters for the ctgan synthesizer fit class. [https://github.com/sdv-dev/CTGAN/issues/25](https://github.com/sdv-dev/CTGAN/issues/25). This allows the user to print basic gpu stats for each epoch running. Probably appeals mostly to people that get a satisfaction from watching their gpu temperature go up ;)

**Comment by Baukebrenninkmeijer** [comment]
Nice project @oregonpillow!

**Comment by csala** [comment]
This is already listed on the README, so I'm closing this issue for now. Great contribution @oregonpillow !
