### ISSUE TITLE
Doubt with Likelihood fitness metric

### ISSUE THREAD

**Issue by vampypandya** [sdv-dev/CTGAN#32]
Hi,

I am trying to understand the  Evaluation Metrics and Framework. You have mentioned that L_(test) will detect Mode Collapse. How does that happen?
Also, it would be great if you could elaborate on "But this metric introduces the prior
knowledge of the structure of S
0 which is not necessarily encoded in Tsyn."

Thanks

**Comment by leix28** [comment]
Hi @vampypandya 

L_test could detect mode collapse. If mode collapse happens, the data simulator S’ will capture only part of the modes. In the test data, all modes will be covered. So, when computing likelihood on modes that are covered by the test data but not covered by S’, we will get very low (bad) likelihood.

Regarding prior knowledge of the structure of S, let’s assume there are 3 variables, A, B and C. B and C are conditionally independent conditionedon A. Such information of conditional independence can be captured by the structure of S (regardless of parameters/probabilities on edges). When we use synthetic data to retrain S’, we use the prior knowledge of conditional independence.. That is we are not requiring that the synthesizer learn structure as well.
