### ISSUE TITLE
Check discrete_columns valid before fitting

### ISSUE THREAD

**Issue by oregonpillow** [sdv-dev/CTGAN#35]
As @csala mentioned in [#24 ](https://github.com/sdv-dev/CTGAN/issues/24#issuecomment-581147311) it would be good to check that `discrete_columns` list is valid at the beginning of fitting instead of silently ignoring invalid columns then throwing an error later in the fitting process.

### What I Did

Would something similar to this at the beginning of `fit`function work? : 
```
for col in discrete_columns:
  if col not in data.columns:
    print("*discrete_columns error*")
    print(col + " not found in data")
    col_error = True
  else:
    col_error = False
if col_error is True:
  sys.exit()
```

**Comment by csala** [comment]
I think that the check could be done in a shorter way, and a `ValueError` should be raised instead of just existing silently (actually, `sys.exit` is something that you will want to use only in CLI code and in very specific circumstances!)

I think that something like this should work:

``` 
invalid_columns = set(discrete_columns) - set(data.columns)
if invalid_columns:
    raise ValueError('Invalid columns found: {}'.format(invalid_columns))
```
