### ISSUE TITLE
CTGAN using deprecated 'sklearn'

### ISSUE THREAD

**Issue by mtas0** [sdv-dev/CTGAN#350]
### Environment Details

* CTGAN version: 0.9.1
* Python version: 3.12

Hi, I cannot install ctgan because it still uses 'sklearn' as one of its dependencies, however 'sklearn' has been deprecated and 'scikit-learn' should be used instead. 

Could you please update your dependencies so that scikit-learn is installed and not sklearn? 

Thank you.

**Comment by npatki** [comment]
Hi @mtas0, nice to meet you.

It is my understanding that even when installing the latest version of scikit-learn, you can still use `import sklearn` within Python to refer to the same (newer) scikit-learn package.

I've double-checked the requirements in the latest [CTGAN stable release](https://github.com/sdv-dev/CTGAN/blob/stable/pyproject.toml#L28). The CTGAN library is requiring `scikit-learn`. It sets a minimal version -- meaning that any newer version of the `scikit-learn` library should be compatible with it.

https://github.com/sdv-dev/CTGAN/blob/c258d865b4ae129e7ba424d0cb522d89c453432f/pyproject.toml#L28-L29

So I'm not sure why this particular requirement would blocking you from installation. Perhaps there is another library in your Python environment that is interfering? Happy to help you debug if you're able to provide more info -- is there an error message you're seeing?

**Comment by npatki** [comment]
Hi @mtas0, I'm closing this issue off since it has been inactive for a few weeks. Please feel free to reply if there's more to discuss on the topic. I can always re-open the issue. Thanks.
