### ISSUE TITLE
Lossvalues are good, but the quality of the synthetic data is bad... How?? HELP WANTED

### ISSUE THREAD

**Issue by ilkayyuksel** [sdv-dev/CTGAN#391]
Hi, I would like to ask a question.

I am using the CTGAN Model for my masterthesis, i want to generate synthetic data using the dataset CIC Collection (https://www.kaggle.com/datasets/dhoogla/cicidscollection) (intrusion detection system dataset, so it contains attacks, there are only numerical features!!). I want to generate synthetic data of a certain attack, doesn't matter which one, I choose to generate fake samples for the attack 'Infiltration', which counts 94857 real samples to train with.
I have trained my CTGAN model with the following code:
```python
from ctgan import CTGAN

ctgan = CTGAN(epochs=600, verbose=True, generator_lr=1e-5, discriminator_lr=1e-6, batch_size=128, pac=2, generator_decay=1e-6,
                 discriminator_decay=1e-6, discriminator_steps=1)
ctgan.fit(real_data, discrete_columns)

```

loss values: 
![image](https://github.com/sdv-dev/SDV/assets/159261558/43c408dd-8620-4d86-a7e1-50302e043229)

metrics from SDV:

KS complement
Average:  0.3587

Result: Despite that the generator and discriminator are stabilizing, the quality of my fake samples is not that good, bad actually.

Then I trained CTGAN synthesizer, this one gonna put some more preprocessing init, but the results are not different.

Why is this happening? My loss values are perfectly shaped according to https://github.com/sdv-dev/SDV/discussions/980

If you need other information, please ask me!
Can you help me guys? I have been struggling with this for a while.....

You can see some of the distributions (see images)

![distribution_Total Fwd Packets](https://github.com/sdv-dev/SDV/assets/159261558/d118e14e-f9fb-485a-9789-6e7166518bfa)
![distribution_Total Backward Packets](https://github.com/sdv-dev/SDV/assets/159261558/5407e059-5823-4b92-bd9b-d09e39ce1a32)
![distribution_Fwd Packets Length Total](https://github.com/sdv-dev/SDV/assets/159261558/37497a56-0f7d-40e7-a7db-ce4d68c5506a)
![distribution_Fwd Packet Length Std](https://github.com/sdv-dev/SDV/assets/159261558/0471ee1f-911c-4368-b991-7c6a51bbd774)
![distribution_Fwd Packet Length Mean](https://github.com/sdv-dev/SDV/assets/159261558/da1114e6-0bf0-4d6b-a64c-83a2be67ce37)
![distribution_Fwd Packet Length Max](https://github.com/sdv-dev/SDV/assets/159261558/fcbf1c9f-a38e-4617-95ed-e2f003298191)
![distribution_Flow Duration](https://github.com/sdv-dev/SDV/assets/159261558/c15a54df-e912-4f08-8c7a-12ba3bf9eba2)
![distribution_Bwd Packets Length Total](https://github.com/sdv-dev/SDV/assets/159261558/87809b90-0023-4fd3-907b-bd0b4739b597)
![distribution_Bwd Packet Length Std](https://github.com/sdv-dev/SDV/assets/159261558/dad600f9-5a60-4f37-af5a-c257d1799088)
![distribution_Bwd Packet Length Mean](https://github.com/sdv-dev/SDV/assets/159261558/042c88dc-fe43-4e6a-88cc-f99040f07dc6)
![distribution_Bwd Packet Length Max](https://github.com/sdv-dev/SDV/assets/159261558/9c0ffea3-3dc3-44f9-80cd-20e3adde70eb)

**Comment by srinify** [comment]
Hi @ilkayyuksel I'll close this issue out since we already have this thread: https://github.com/sdv-dev/SDV/issues/2010
