### ISSUE TITLE
There was a problem generating data when specifying column names and  value

### ISSUE THREAD

**Issue by xiaoming-mk** [sdv-dev/CTGAN#397]
### Environment Details

Please indicate the following details about the environment in which you found the bug:

* CTGAN version:
* Python version:3.9
* Operating System:windows

### Error Description
synthetic_data = ctgan.sample(1000）
The above line of code runs fine, but when I add conditional values, there are some problems!
synthetic_data = ctgan.sample(1000, condition_column="sex", condition_value="Male")

### Steps to reproduce

from ctgan import CTGAN
from ctgan import load_demo

real_data = load_demo()

# Names of the columns that are discrete
discrete_columns = [
    'workclass',
    'education',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'native-country',
    'income'
]

ctgan = CTGAN(epochs=10)
ctgan.fit(real_data, discrete_columns)

# Create synthetic data
synthetic_data = ctgan.sample(1000, condition_column="sex", condition_value="Male")
print(synthetic_data)

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
  warnings.warn(
Traceback (most recent call last):
  File "E:\oops\code\CTGAN-main\CTGAN-main\ctgan\train.py", line 23, in <module>
    synthetic_data = ctgan.sample(1000, condition_column="sex", condition_value="Male")
  File "E:\oops\code\CTGAN-main\CTGAN-main\ctgan\synthesizers\base.py", line 50, in wrapper
    return function(self, *args, **kwargs)
  File "E:\oops\code\CTGAN-main\CTGAN-main\ctgan\synthesizers\ctgan.py", line 492, in sample
    condition_info = self._transformer.convert_column_name_value_to_id(
  File "E:\oops\code\CTGAN-main\CTGAN-main\ctgan\data_transformer.py", line 260, in convert_column_name_value_to_id
    raise ValueError(f"The value `{value}` doesn't exist in the column `{column_name}`.")
ValueError: The value `Male` doesn't exist in the column `sex`.

**Comment by xiaoming-mk** [comment]
I have found the solution to the problem[https://github.com/sdv-dev/CTGAN/issues/233]

**Comment by npatki** [comment]
Thanks for confirming @xiaoming-mk. I'll close this off as a duplicate and we'll hope to fix the underlying issue soon.
