### ISSUE TITLE
Getting negative values for some features?

### ISSUE THREAD

**Issue by kitty54** [sdv-dev/CTGAN#40]
Why am I getting negative values for feature like 'charges' or in case of demo dataset the feature 'capital-gain'?

**Comment by oregonpillow** [comment]
This has already been addressed here [Issue24](https://github.com/sdv-dev/CTGAN/issues/24#issuecomment-603897028 )

capital-gain column is continuous and the column is filled with mostly zeros punctuated occasionally by some non-zero values. When the model fits, it's learning the distribution of values. The model will try to gaussian fit around zero but will of course result in some values below zero as well.
