### ISSUE TITLE
Likelihood of the generated data regarding the real data

### ISSUE THREAD

**Issue by celsofranssa** [sdv-dev/CTGAN#401]
What metrics could we apply to measure the likelihood of the generated data regarding the real data?

**Comment by 19956406179** [comment]
I also want to know, if I just: pip install ctgan, and then write a piece of code to use CTGAN to generate synthetic data for my dataset, how can I evaluate whether the generated data is good or bad

**Comment by npatki** [comment]
Hi @celsofranssa and @19956406179, great to see interest in CTGAN. 

I would recommend looking into the [SDMetrics library](https://docs.sdv.dev/sdmetrics) for anything metrics-related. There is a [Quality Report](https://docs.sdv.dev/sdmetrics/reports/quality-report/whats-included) you can run for a general estimate of data quality, [visualization utilities](https://docs.sdv.dev/sdmetrics/reports/visualization-utilities), and other speciality metrics such as [Data likelihood](https://docs.sdv.dev/sdmetrics/metrics/metrics-in-beta/data-likelihood).

BTW -- while you are welcome to try using CTGAN as a standalone library, we actually recommend using it via the SDV library instead. Within SDV, the [CTGANSynthesizer](https://docs.sdv.dev/sdv/single-table-data/modeling/synthesizers/ctgansynthesizer) is a wrapper around this one, but it allows additional features such as data pre-processing, as well as more convenient visualizations, metrics, etc.

**Comment by npatki** [comment]
Closing this issue off since it's been inactive for a few weeks and there are a few suggestions in the previous comment. Please feel free to reply if there is more to discuss around this topic, and I can always reopen as needed.
