### ISSUE TITLE
Feature request: Joint/3D tabular data 

### ISSUE THREAD

**Issue by tolandwehr** [sdv-dev/CTGAN#41]
Hi there,

on the way on shaping my own CGAN I stumbled upon your application which is indeed quite meaty and impressive. As you're someway ahead of my application I just wanted to ask whether it might be appendable by a certain feature:  

Right now, the generation is 2d, so each line is regarded as a single, independent output. In my respective data set, the data is structured as follows: (object, year, features). It displays the development of features of an object during a certain time frame (e.g. 20 years); some of them are static (like size=1.89,1.89,1.89,1.89...), some subjects to change over a time (like, e.g., the age: 1,2,3,4... or weight=80,78.4,77.2,74.2...).  A GAN output would thus ideally (and maybe quite similar to image generation) produce (1,20,feature) outputs that would display a connectedness of data within the year frame. Not certain how to implement this neatly within your code right now, but it would be highly appreciated ;-).

Regards,
Tobias

**Comment by tolandwehr** [comment]
Hi there!

Just wanted to ask, whether this might be actually worthwhile feature for you folks (that might be even already on the update list) or something you wouldn't consider in near future.

Regards,
Tobias

**Comment by leix28** [comment]
Hi @tolandwehr ,

I think this feature is related to synthesizing a database. In a database, there are multiple tables. In your example, there are some two tables. One contains (object_id, static_features), and the other contains (object_id, year_id, dynamic features). The latter one also requires the capability of generating time-series data. I would not consider adding this feature to CTGAN project in the near feature. But we do have some a related project [SDV](https://github.com/sdv-dev/SDV). SDV can generate tables hierarchical structure.

**Comment by csala** [comment]
Closing this as, like @leix28 said, this is being worked on in the related project [SDV](/sdv-dev/SDV) Don't forget to check it out!
