### ISSUE TITLE
Time Series

### ISSUE THREAD

**Issue by firmai** [sdv-dev/CTGAN#42]
Hi do you perhaps know or have you yourself developed a generative model for multivariate time series. Thanks for the package!

**Comment by leix28** [comment]
We are developing GAN-based algorithms for multivariate time series. But these methods haven't been open-sourced yet.

**Comment by firmai** [comment]
That is excellent news, I saw a gap in that there is no nicely packaged version out there. Looking very much forward.

**Comment by adamFinastra** [comment]
Any update on any time series methods?
