### ISSUE TITLE
Saving a CTGAN model

### ISSUE THREAD

**Issue by diegobodner** [sdv-dev/CTGAN#44]
* CTGAN version:
* Python version:
* Operating System:

### Description
I would like to save in disk a CTGAN trained model. I did it in the past using TGAN using tgan.save command.

### What I Did
It seems it's not possible to save models
```
Thanks for your jelp
```

**Comment by kishensurajp** [comment]
@diegobodner , did saving as pickle work?

**Comment by oregonpillow** [comment]
Hi @diegobodner, You need to `import torch` explicitly somewhere.

assuming you called your instance of the synthesiser 'ctgan' then it's pretty simple:

```
torch.save(ctgan,'my_awesome_model')
loaded_model = torch.load('my_awesome_model')
sample = loaded_model.sample(500)
```

Here's an example:
[https://colab.research.google.com/drive/1YBxeOlsATKt6zesv_O3HPCPR-G8sPPib](https://colab.research.google.com/drive/1YBxeOlsATKt6zesv_O3HPCPR-G8sPPib)

however, I'm currently getting  `ImportError: cannot import name '_is_url'` error now when returned the sampled pandas data frame. Not sure if this is unique to the ColabNotebook I'm running in.

**Comment by diegobodner** [comment]
Many thanks!!

torch.save(ctgan,'my_awesome_model') works well.

Best regards

**Comment by kveerama** [comment]
Thanks @oregonpillow. Closing this for now.

**Comment by RedBlue01** [comment]
> Hi @diegobodner, You need to explicitly somewhere.`import torch`
> 
> assuming you called your instance of the synthesiser 'ctgan' then it's pretty simple:
> 
> ```
> torch.save(ctgan,'my_awesome_model')
> loaded_model = torch.load('my_awesome_model')
> sample = loaded_model.sample(500)
> ```
> 
> Here's an example: https://colab.research.google.com/drive/1YBxeOlsATKt6zesv_O3HPCPR-G8sPPib
> 
> however, I'm currently getting error now when returned the sampled pandas data frame. Not sure if this is unique to the ColabNotebook I'm running in.`ImportError: cannot import name '_is_url'`

I can't thank you enough.
