### ISSUE TITLE
Validity of single samples

### ISSUE THREAD

**Issue by Ped45** [sdv-dev/CTGAN#45]
I'm using CTGAN to generate a synthetic population of travel records. Some of my columns are deterministically correlated, for example, *column A + 60 x column B = column C*. 

After training, the model does not capture these correlations within single samples. This means for a single sample: *column A + 60 x column B =/= column C*. However, the generated population consisting of many samples captures the correlation as *avg(column A) + 60 x avg(column B) = avg(column C)*. 

As I need single samples to be valid, I was wondering if there are **parameters in the code that allow  to account for more correlation within single samples**? Of course for deterministic correlations this does not make sense as they are easy to generate manually afterwards, but there are other correlations in my data for which it does make sense (e.g. age and years of driving experience).

**Comment by csala** [comment]
This kind of columnar relationships is what we call constraints, which CTGAN is not intended to handle for now. However, work is being done to handle them properly in the related project [SDV](/sdv-dev/SDV). Please check it out!
