### ISSUE TITLE
handling NaNs and datatypes not perseved

### ISSUE THREAD

**Issue by farquasar1** [sdv-dev/CTGAN#48]
* CTGAN version: '0.2.2.dev0'
* Python version: 3.6
* Operating System: macOS

### Description
1. Through an error on fit if a categorical columns has any NaN
2. in sampling datatypes returned are not preserved - on Adult data int are returned as categorical

### What I Did
ctgan = CTGANSynthesizer()
ctgan.fit(data, discrete_columns, epochs=50)

**Comment by csala** [comment]
Hi @farquasar1 I'm afraid that the question is not clear. Would you mind providing some more details about what you are asking and what are the exact commands required to reproduce the behavior that you describe?

**Comment by Baukebrenninkmeijer** [comment]
@farquasar1 Would you not want to substitute NaN values with a placeholder? That way, you can model them with the GAN. Otherwise, you can never model data that has any missing values. 

For example, as a preprocessing step i'm doing this:
```
        df.loc[:, self.categorical_columns] = df.loc[:, self.categorical_columns].fillna('[NAN]')
```
And then, when sampling you just do 
```
        df = df.replace(to_replace='[NAN]', value={a: None for a in self.categorical_columns})
```

**Comment by csala** [comment]
Both `NaN` values and data types are properly handled when [using CTGAN through SDV](https://sdv.dev/SDV/user_guides/single_table/ctgan.html), so this issue can be closed.
