### ISSUE TITLE
Can developers get more documentation for better understanding the code

### ISSUE THREAD

**Issue by sree369nidhi** [sdv-dev/CTGAN#49]
hi, I came across this repo few days ago I'm really impressed by the outputs of the model but I'm having a very hard time understanding the whole code in a clear manner. Is it possible for you guys to help me out.

**Comment by csala** [comment]
Work is currently being done to improve the quality (and readability) of the code. After the changes are done it should be much easier to read it and understand everything that is going on.

Closing this for now, but stay tuned for the changes and feel free to open a new issue (or re-open this) for any clarifications once the refactoring has been finished.
