### ISSUE TITLE
Code implementations of the VGM that aims to estimate the number of modes of the continuous column

### ISSUE THREAD

**Issue by AshiakerWang** [sdv-dev/CTGAN#56]
It's said in the [ CTGAN pape](https://arxiv.org/pdf/1907.00503.pdf)r that **the number of the modes** of the continuous column is estimated with variational Gaussian mixtures model (VGM). 

However, after going through the code, I could not find the corresponding implementations of the  variational Gaussian mixtures model that aims to estimate the number of modes.  It seems that the number of modes of continuous columns is set default to 10 according the following snippets.
https://github.com/sdv-dev/CTGAN/blob/cb984fc1dea6822c329213821ab6af670c3425cd/ctgan/transformer.py#L23-L34

, Or I have missed some other lines that estimate the number of modes.

It will be appreciated if you could resolve my doubts.

**Comment by leix28** [comment]
Hi, VGM is also called Bayesian Gaussian Mixture. The VGM uses a Dirichlet process to determine the number of modes. Ideally, the number of modes in VGM has no upper bound. However, we use sklearn's implementation, so we have to set the maximum number of Gaussian mixtures. By default, we set the maximum number of modes to be 10. And for most continuous columns, the model does not use up all 10 modes.

**Comment by AshiakerWang** [comment]
Thanks a lot for your explanation!
