### ISSUE TITLE
support recent versions of pandas

### ISSUE THREAD

**Issue by yairdata** [sdv-dev/CTGAN#57]

**Comment by hannahawalsh** [comment]
I too would like support of pandas 1.0 because I have other code that depends on that.

**Comment by MotoRZR** [comment]
Ditto

**Comment by csala** [comment]
The latest version in `master` branch now supports both the latest `pandas` and `scikit-learn` versions and the change will be included in the next release, so I'm adding this to the next milestone and closing the issue for now.
