### ISSUE TITLE
Trying to modify batch size in source code (synthesizer.py) from 500 to 16 and getting 'Assertion error'

### ISSUE THREAD

**Issue by Ujjwalsas9** [sdv-dev/CTGAN#60]
* CTGAN version: 0.2.1
* Python version: 3.7
* Operating System: Windows 10

### Description
My raw data file to very small so I was trying to generate synthetic data with modified source code with batch size=16 but I am getting assertion error. Please let me know what should I do.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Baukebrenninkmeijer** [comment]
In my tests, batch size needs to be a multiple of 10. I don't recall why this issue was again specifically.

**Comment by k15z** [comment]
The discriminator uses the PacGAN framework to prevent mode collapse with pack size 10. @csala The docstring can be updated to clarify this restriction, the batch size must be divisible by the `pack_size`.

**Comment by elisim** [comment]
In addition, `batch_size` option should be moved to `fit` function instead of in the `CTGANSynthesizer` ctor. 
Now:

`
ctgan = CTGANSynthesizer(batch_size=128)
`

How it should be (IMHO):

`
ctgan.fit(data, discrete_columns, epochs=3, batch_size=128)
`

**Comment by csala** [comment]
> The discriminator uses the PacGAN framework to prevent mode collapse with pack size 10. @csala The docstring can be updated to clarify this restriction, the batch size must be divisible by the `pack_size`.

Thanks @k15z, I opened [an issue on SDV](https://github.com/sdv-dev/SDV/issues/211) to add this to the CTGAN model documentation, so I'm closing this one for now.

> In addition, `batch_size` option should be moved to `fit` function instead of in the `CTGANSynthesizer` ctor.
> Now:
> 
> `ctgan = CTGANSynthesizer(batch_size=128)`
> 
> How it should be (IMHO):
> 
> `ctgan.fit(data, discrete_columns, epochs=3, batch_size=128)`

Thanks for the suggestion @elisim, but this was discussed [a long time ago](5) and we decided to move in another direction, so we will try to keep the hyperparameter organization as it is right now.

Also, bear in mind that we are pushing it even further when [using CTGAN from SDV](https://sdv.dev/SDV/user_guides/single_table/ctgan.html), where all the hyperparameters and setup arguments are passed when the model is created and the only input argument for the `fit` method is the data to which the model is fitted.
