### ISSUE TITLE
Applying CTGAN to single colum?

### ISSUE THREAD

**Issue by gautambak** [sdv-dev/CTGAN#64]
Hi there 

I’m wondering if there is a way to use CTGAN on a single column ? For example if I have a dataframe with 100 columns but only want to generate Data for one column by leveraging relationship in other columns ?

**Comment by oregonpillow** [comment]
Hi @gautambak ,
The general attitude here is sampling is cheap therefore generally recommended to sample as normal then modify the output to your own specific needs. 

For your needs, sample then simply cut off columns you don't want.

**Comment by gautambak** [comment]
Hi @oregonpillow 

Thank you for your speedy reply!  

I'm not 100% clear. If I have 100 columns and want to leverage 99 of them to enrich/create data for 1 column, how can I use sampling? If I generate the rows of data, wouldn't the all the columns not all match?

**Comment by oregonpillow** [comment]
> only want to generate Data for one column by leveraging relationship in other columns

I interpret this as meaning you want to train a model on a large dataset but when you synthesise data (which means sampling from your trained model), you only want to create data for one of the columns in your original dataset?

E.g. You have a dataset that has 3 columns: age, income, sex.   After you train the model you are only interested in producing synthetic data for income so you sample from your model as normal (which produces 'x' rows with 3 columns) but then delete the columns age and sex which you don't want.
Is this not essentially what you want?

> wouldn't the all the columns not all match?
not sure what you mean by this? There would only be 1 column. And each row would represent a value that was learned by the other columns before you deleted them.

If this is not correct please can elaborate further.

**Comment by csala** [comment]
@gautambak what you are describing sounds like just a standard supervised tabular machine learning problem, where you are learning how to predict the value of one column based on the values on the other ones. Is that so?

**Comment by gautambak** [comment]
Hi @oregonpillow 

That is correct but I'm not deleting age, sex.  

To use your example, my usecase would be I have 50% data of income, and 100% of age & sex.  I know I can use a regression model but I wanted to try to use CTGAN to create values for the missing income data, then merge it with the original dataframe where the data was missing.


@csala Yes you are correct. I'm not sure is CTGAN is the best solution but from what I've seen it looks like it can be a good fit for my problem.

**Comment by fibarrola** [comment]
@gautambak I think you'll need to modify the 'sample' behavior on object 'CTGANSynthesizer' to allow for synthesizing using from a 'condvec' input

**Comment by gautambak** [comment]
> @gautambak I think you'll need to modify the 'sample' behavior on object 'CTGANSynthesizer' to allow for synthesizing using from a 'condvec' input

Thank you for this @fibarrola - I went through the code and found the sample function and the condvec references but I'm unsure what I would need to do to get the behaviour I'm looking for.  

Is there something in this block that I should change?

```
def sample(self, n):
        """Sample data similar to the training data.

        Args:
            n (int):
                Number of rows to sample.

        Returns:
            numpy.ndarray or pandas.DataFrame
        """

        steps = n // self.batch_size + 1
        data = []
        for i in range(steps):
            mean = torch.zeros(self.batch_size, self.embedding_dim)
            std = mean + 1
            fakez = torch.normal(mean=mean, std=std).to(self.device)

            condvec = self.cond_generator.sample_zero(self.batch_size)
            if condvec is None:
                pass
            else:
                c1 = condvec
                c1 = torch.from_numpy(c1).to(self.device)
                fakez = torch.cat([fakez, c1], dim=1)

            fake = self.generator(fakez)
            fakeact = self._apply_activate(fake)
            data.append(fakeact.detach().cpu().numpy())

        data = np.concatenate(data, axis=0)
        data = data[:n]

        return self.transformer.inverse_transform(data, None)

```

**Comment by gautambak** [comment]
Follow up, related question - once I even generate the results, how can I join them? Using the sample code, it generates the entire dataset.

**Comment by ninamwa** [comment]
Hi @gautambak. Have you done any more work on this? I think I am looking for kind of the same behavior as you do :-)

**Comment by gautambak** [comment]
Hi @ninamwa No luck/progress on my side. I couldn't figure it out.

**Comment by csala** [comment]
I'd like to add some light to this topic and, if everything is clear, maybe we should close this issue to avoid future confusions.

What I think @gautambak and @ninamwa are trying to achieve is not really what CTGAN is intended for, since their goal seems to be to generate random values for a single variable based on fixed values for all the other variables. Is that right?

But CTGAN actually works the other way around: it generates random values for all the variables based on, at most, the fixed value of one of them. So, if that is what you are really trying to achieve, I'm afraid that CTGAN is not the tool which you are looking for, at least not as an all-in-one end-to-end solution.

In any case, in the future we do not discard working on the possibility of sampling from N random variables conditioning on M other variables, but that would be something that escapes the current CTGAN architecture and which would probably need a major rework of the project, so I think that we can close this issue and open a new one with all the details when the time comes to work on it.
