### ISSUE TITLE
Cant install CTGAN

### ISSUE THREAD

**Issue by apavlo89** [sdv-dev/CTGAN#65]
* CTGAN version: latest
* Python version: 3.7.7
* Operating System: Windows 10 home

### Description

When trying to install ctgan i get the following error:

ERROR: Could not find a version that satisfies the requirement torch<2,>=1.0 (from ctgan) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<2,>=1.0 (from ctgan)

### What I Did

```
pip install ctgan
```

I also banged my fist on the desk...

**Comment by oregonpillow** [comment]
try `pip install --upgrade torch` . I'm assuming your pip is mapped to python3 version of pip?  Because normally pip3 is used to specify the python3 version of pip. e.g. pip3 install ctgan

**Comment by csala** [comment]
Hi @apavlo89 

As @oregonpillow suggested, I think you can try to install PyTorch **before** installing ctgan.

You can find instructions to install PyTorch only for your particular setup here: https://pytorch.org/get-started/locally/

**Comment by apavlo89** [comment]
Thank you, it is now working properly!
