### ISSUE TITLE
could not convert string to float: 'workclass'

### ISSUE THREAD

**Issue by imutyshev** [sdv-dev/CTGAN#67]
* CTGAN version: latest
* Python version: 3.7.4
* Operating System: Ubuntu 18.04 on WSL

### Description

I am trying to run demo, but get 'could not convert string to float: 'workclass'.

### What I Did

from ctgan import load_demo
from ctgan import CTGANSynthesizer

demo = load_demo()

discrete_columns = [
    'workclass',
    'education',
    'marital-status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'native-country',
    'income'
]

ctgan.fit(demo, discrete_columns)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-36-a5064798ee49> in <module>
----> 1 ctgan.fit(demo, discrete_columns)

~/anaconda3/lib/python3.7/site-packages/ctgan/synthesizer.py in fit(self, train_data, discrete_columns, epochs, log_frequency)
    116 
    117         self.transformer = DataTransformer()
--> 118         self.transformer.fit(train_data, discrete_columns)
    119         train_data = self.transformer.transform(train_data)
    120 

~/anaconda3/lib/python3.7/site-packages/ctgan/transformer.py in fit(self, data, discrete_columns)
     73                 meta = self._fit_discrete(column, column_data)
     74             else:
---> 75                 meta = self._fit_continuous(column, column_data)
     76 
     77             self.output_info += meta['output_info']

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/_testing.py in wrapper(*args, **kwargs)
    325             with warnings.catch_warnings():
    326                 warnings.simplefilter("ignore", self.category)
--> 327                 return fn(*args, **kwargs)
    328 
    329         return wrapper

~/anaconda3/lib/python3.7/site-packages/ctgan/transformer.py in _fit_continuous(self, column, data)
     33             n_init=1
     34         )
---> 35         gm.fit(data)
     36         components = gm.weights_ > self.epsilon
     37         num_components = components.sum()

~/anaconda3/lib/python3.7/site-packages/sklearn/mixture/_base.py in fit(self, X, y)
    190         self
    191         """
--> 192         self.fit_predict(X, y)
    193         return self
    194 

~/anaconda3/lib/python3.7/site-packages/sklearn/mixture/_base.py in fit_predict(self, X, y)
    217             Component labels.
    218         """
--> 219         X = _check_X(X, self.n_components, ensure_min_samples=2)
    220         self._check_initial_parameters(X)
    221 

~/anaconda3/lib/python3.7/site-packages/sklearn/mixture/_base.py in _check_X(X, n_components, n_features, ensure_min_samples)
     51     """
     52     X = check_array(X, dtype=[np.float64, np.float32],
---> 53                     ensure_min_samples=ensure_min_samples)
     54     if n_components is not None and X.shape[0] < n_components:
     55         raise ValueError('Expected n_samples >= n_components '

~/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, warn_on_dtype, estimator)
    529                     array = array.astype(dtype, casting="unsafe", copy=False)
    530                 else:
--> 531                     array = np.asarray(array, order=order, dtype=dtype)
    532             except ComplexWarning:
    533                 raise ValueError("Complex data not supported\n"

~/anaconda3/lib/python3.7/site-packages/numpy/core/_asarray.py in asarray(a, dtype, order)
     83 
     84     """
---> 85     return array(a, dtype, copy=False, order=order)
     86 
     87 

ValueError: could not convert string to float: 'workclass'

**Comment by jari-el13** [comment]
Where you able to resolve the issue?

**Comment by imutyshev** [comment]
> 
> 
> Where you able to resolve the issue?

yes, but indirectly. I used ctgan from sdv (https://github.com/sdv-dev/SDV) and it worked fine. BTW ctgan poorly handles accounting data. So if you need to generate syntethic accounting transactaion log CTGAN is a poor choice.
