### ISSUE TITLE
Hello I have a question. can I make new dataset only from time series. 

### ISSUE THREAD

**Issue by dosoung** [sdv-dev/CTGAN#70]
* CTGAN version:
* Python version:
* Operating System:

### Description

Hello, My name is DOHYUN SOUNG who is bachelor student in Korea.
I want to generate dataset from my original data. That's why I used your CTGAN.
It's really nice and awesome. But, I need to make new dataset by my time series column.
When I used your model. It only creates time series data that already exists. I want to multiply the data on the new date.
Can you give me answer? 
Thank you so much
### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by dosoung** [comment]
<img width="266" alt="Screen Shot 2020-09-03 at 2 14 28 PM" src="https://user-images.githubusercontent.com/48678405/92073921-cec1de80-edef-11ea-90ef-e825909398fc.png">

above my image is my dataset when I used your model. it makes new dataset but its only depend on my time data.
In other words, I want to make new time series data for example,  2018-07-05 , 2018-02-04 like this one.
I don't generate original time data

**Comment by csala** [comment]
Hello @dosoung we have recently introduced Timeseries models in https://github.com/sdv-dev/SDV!

You can find more details here: https://sdv.dev/SDV/user_guides/timeseries/par.html
