### ISSUE TITLE
Limit the value of some variables

### ISSUE THREAD

**Issue by JulienGervai** [sdv-dev/CTGAN#72]
* CTGAN version: latest
* Python version: 3.8.3
* Operating System: Windows 10

### Description
I would like to know if there is a way to limit the value that can take a non discrete variable.
For example if I have a variable named "age" which represent the age of some people, or a variable named "charges" which represent the charges you have to pay for something. These two variables cannot be negatives. For the variable "age", we can assume that the values won't be higher than 150 for example.

I saw that in the method **sample**  of CTGANSynthesizer we can give condition_column and condition_value. Is there a way to solve my problem with that ?

**Comment by csala** [comment]
Hi @JulienGervai this issue is already being worked on in https://github.com/sdv-dev/SDV

Please have a look at this issue, which offers a few ways to get this working properly: https://github.com/sdv-dev/SDV/issues/200

**Comment by JulienGervai** [comment]
Thank you @csala I am checking and it looks very good.
