### ISSUE TITLE
Error running the demo

### ISSUE THREAD

**Issue by jhleonjg** [sdv-dev/CTGAN#74]
* CTGAN version: 0.2.2.dev2
* Python version: 3.7.5
* Operating System: Windows

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Tried to run the demo by typing:

### What I Did in the command line:
import ctgan
data = lead_demo()
discrete_columns = ['workclass','education','marital_status', 'occupation','relationship','race','sex','native-country','income']
from ctgan import CTGANSynthesizer
ctgan = CTGANSynthesizer()
ctgan.fit(data, discrete_columns, epochs = 5)

Then an error came line 85 of the _asarray.py when the line 118 of synthesizer is call. I tried to send an image of the error below but the image does not loads.
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
![Error_1](https://user-images.githubusercontent.com/26063334/97011164-3cf86700-153e-11eb-9a00-5731e24464fc.PNG)

**Comment by csala** [comment]
Hi @jhleonjg 

There is a typo on the name of the `marital-status` column, which you wrote as `marital_status`.

Please make sure to copy and paste the examples, so you make sure that everything is written as expected.
