### ISSUE TITLE
Using sdv.ctgan or ctgan implementation using this repo?

### ISSUE THREAD

**Issue by elisim** [sdv-dev/CTGAN#75]
Hey,

I'm trying to modify CTGAN code. Unfortunately, it seems like the implementation here is missing core features (for example, handling NaNs in the dataset [1][2])
I looked for [sdv.ctgan](https://sdv.dev/SDV/user_guides/single_table/ctgan.html), but it's not clear how to modify CTGAN code through sdv.

What is the proper way for doing that?
Thanks

[1] [Not able to fit() CTGANSynthesizer() if NaNs are present in the dataset ](https://github.com/sdv-dev/CTGAN/issues/21)
[2] [handling NaNs and datatypes not perseved](https://github.com/sdv-dev/CTGAN/issues/48)

**Comment by csala** [comment]
Hello @elisim 

If I understand the question properly, what you are asking is "How do I setup my development environment so I can modify the CTGAN code but still use it through SDV, so I can have all the advantages that it provides, like handling NaNs?"

If this is what you are asking, what you need to do is the following:

1. Clone CTGAN: `git clone git@github.com:sdv-dev/CTGAN`
2. Create the virtualenv (or conda environment) in which you will be working.
3. Install CTGAN in development mode: `make install-develop`.
4. Install `sdv` in the same virtualenv: `pip install sdv`

At this point, when you use `sdv.tabular.CTGAN`, under the hood it will be using the `CTGANSynthesizer` that you have in the `ctgan` folder from inside the CTGAN repository folder.

If you want to go even further and also modify the SDV code (for example, to pass new hyperparameters or arguments), you should also add steps to clone and install SDV in development mode within the same virtualenv.

Altogether, the setup would be:

```bash
git clone git@github.com:sdv-dev/SDV
git clone git@github.com:sdv-dev/CTGAN
mkvirtualenv -p $(which python3.8) ctgan-dev
cd SDV
make install-develop
cd ../CTGAN
make install-develop
```

At this point, when you use `sdv.tabular.CTGAN`, it will be using the code from the two repositories that you cloned.

**Comment by csala** [comment]
Also @elisim just curious: What modifications are you doing?

Maybe you could open issues describing what you want to achieve so we can discuss how to approach the changes and eventually make them part of the project? Also, please feel free to ping me on slack if you want to discuss the changes there first.

**Comment by elisim** [comment]
Thank you for your detailed answer. 
Regarding my modifications, I will open an issue if it will be relevant to apply into CTGAN. 

Thanks
