### ISSUE TITLE
Unknown category in sample()

### ISSUE THREAD

**Issue by ZagHe568** [sdv-dev/CTGAN#76]
* CTGAN version: 0.2.2
* Python version: 3.6
* Operating System: CentOS Linux release 7.8.2003

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

Trying to generate samples condition on one column.

### What I Did

ctgan.sample(1000, "workclass", "Private")
Just tried to run the code in QuickStart documentation.

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-3a0ca7131b58> in <module>
----> 1 samples = ctgan.sample(1000, "workclass", "Private")

~/miniconda3/envs/tgan/lib/python3.6/site-packages/ctgan/synthesizer.py in sample(self, n, condition_column, condition_value)
    251         if condition_column is not None and condition_value is not None:
    252             condition_info = self.transformer.covert_column_name_value_to_id(
--> 253                 condition_column, condition_value)
    254             global_condition_vec = self.cond_generator.generate_cond_from_condition_column_info(
    255                 condition_info, self.batch_size)

~/miniconda3/envs/tgan/lib/python3.6/site-packages/ctgan/transformer.py in covert_column_name_value_to_id(self, column_name, value)
    197             "discrete_column_id": discrete_counter,
    198             "column_id": column_id,
--> 199             "value_id": np.argmax(info["encoder"].transform([[value]])[0])
    200         }
    201 

~/miniconda3/envs/tgan/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py in transform(self, X)
    388         check_is_fitted(self)
    389         # validation of X happens in _check_X called by _transform
--> 390         X_int, X_mask = self._transform(X, handle_unknown=self.handle_unknown)
    391 
    392         n_samples, n_features = X_int.shape

~/miniconda3/envs/tgan/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py in _transform(self, X, handle_unknown)
    122                     msg = ("Found unknown categories {0} in column {1}"
    123                            " during transform".format(diff, i))
--> 124                     raise ValueError(msg)
    125                 else:
    126                     # Set the problematic rows to an acceptable value and

ValueError: Found unknown categories ['Private'] in column 0 during transform

**Comment by csala** [comment]
Hi @ZagHe568 it seems there is a typo in the README instructions.

If you inspect the data you will notice that the workclass values in the dataset actually contain an empty space ` ` that precede the actual string:

```python
In [1]: from ctgan import load_demo

In [2]: data = load_demo()

In [3]: data['workclass'].head().to_numpy()
Out[3]: 
array([' State-gov', ' Self-emp-not-inc', ' Private', ' Private',
       ' Private'], dtype=object)
```

So the call should actually look like this:

```python
samples = ctgan.sample(1000, 'workclass', ' Private')
```

**Comment by csala** [comment]
I already pushed the typo fix to the README.

Please @ZagHe568 feel free to reopen if it continues to fail.
