### ISSUE TITLE
ModuleNotFoundError using CTGAN 0.2.2

### ISSUE THREAD

**Issue by privacyabout** [sdv-dev/CTGAN#89]
* CTGAN version: 0.2.2
* Python version: 3.8.5
* Operating System: Ubuntu 16.04

### Description

Describe what you were trying to get done.
I am just starting with CTGAN and hence trying to replicate the instructions. 

Tell us what happened, what went wrong, and what you expected to happen.
- I did install ctgan using pip successfully. (pip install ctgan)
- I was using trying to load some data using ctgan.load_demo ( from ctgan import load_demo)
- I got the error: "ModuleNotFoundError: No module named 'packaging' "
- I checked that CTGAN 0.2.2 released just today. Please suggest if I am missing something or there is a bug in the current release.

### What I Did

```
Paste the command(s) you ran and the output.
from ctgan import load_demo

If there was a crash, please include the traceback here.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rajesh/anaconda3/envs/CTGAN/lib/python3.8/site-packages/ctgan/__init__.py", line 10, in <module>
    from ctgan.synthesizer import CTGANSynthesizer
  File "/home/rajesh/anaconda3/envs/CTGAN/lib/python3.8/site-packages/ctgan/synthesizer.py", line 3, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'

```

**Comment by csala** [comment]
Hi @privacyabout 

I'm afraid we recently added the `packaging` dependency but failed to add it to the `setup.py` of the project.
And, unfortunately, it somehow sneaked through our tests and made it into the release.

We will add it to the `setup.py` before the next release, but in the meantime you can work around it by simply running installing `packaging` with `pip`:

```bash
pip install packaging
```
