### ISSUE TITLE
Implement model_dir parameter use

### ISSUE THREAD

**Issue by williamjduhe** [sdv-dev/CTGAN#9]
* CTGAN version: stable
* Python version: 3.7.5
* Operating System: Ubuntu 18.04

### Description

When specifying the model_dir parameter - no model is saved. This is because the parameter is never checked for  within the CLI to perform a save operation. Pretty straight forward fix to write a method to accomplish this when you run the CLI with the param. I think I will try and create a MR this week for it.

### What I Did

Ran the CLI with example data and the model_dir parameter. 

```
mkdir examples/test_model
python3 -m ctgan.cli --data examples/adult.dat --meta examples/adult.meta --model_dir examples/test_model
```

**Comment by csala** [comment]
Hi @williamjduhe thanks for highlighting this!

Regarding the PR, that would be awesome! However, this week we are precisely working on a code reorganization that will, among other things, change the CLI interface.

So, maybe it would be better if you wait until these changes are in?

**Comment by csala** [comment]
> Regarding the PR, that would be awesome! However, this week we are precisely working on a code reorganization that will, among other things, change the CLI interface.

These changes will be implemented in #10

**Comment by csala** [comment]
At the end issue #10 was closed without this change, so this will go into the next release.

**Comment by fealho** [comment]
Closing the issue, seeing as the `model_dir` parameter doesn't exist anymore.
