### ISSUE TITLE
CTGAN generates negative numerical values for a column containing only positive values.

### ISSUE THREAD

**Issue by HarisNaveed17** [sdv-dev/CTGAN#94]
* CTGAN version: 0.22
* Python version:3.6.9 (Google Colab)
* Operating System: Ubuntu 18.04

### Description
Hello, 
Thank you for open-sourcing your work. It's quite useful and educational.

I'm trying to generate synthetic examples from the Telecom Italia data set. The set contains two continuous columns that contain values between an order of 10^-2 and 10^1. All of these values are >=0.

However, the same data columns generated by the CTGAN feature a significant amount of negative values, at least 3,000 in a generated data set of 23,000. 

I thought this may be because of the small values in the columns, so I scaled the values in the original data by a 100, but this only resulted in negative values of the new order. Which I guess means that the GAN has generated a distribution that contains negative values from a distribution that is strictly positive. This issue does not occur for the only other continuous column. 

What can be the cause of this? Am I missing something obvious? Thanks!

**Comment by fealho** [comment]
Hi @HarisNaveed17 I recommend using [CopulaGAN](https://sdv.dev/SDV/user_guides/single_table/copulagan.html) from SDV if you want to add constraints to the generated data. CTGAN simply fits a gaussian to your data, so a few of the generated results will may end up negative.

**Comment by lindseyrayborn** [comment]
Hi, if I use CopulaGAN do I use the same citation as for CTGAN or a different one?

**Comment by fealho** [comment]
Hi @lindseyrayborn would you mind opening a new issue with your question? That way we can keep things more organized, and other users with the same question can find the solution more easily.
